name: 02 - Workflow Events
on:
    push:
    pull_request:
    schedule:
        - cron: "*/5 * * * *" # Every 5 minutes
    workflow_dispatch:

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: "Show the trigger"
              uses: actions/setup-node@v3
              with:
                  node-version: "16"
            - run: echo "Hello ${{ github.actor }}, World! - ${{ github.event_name }} event"
    # second_job:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: "Show the trigger"
    #           uses: actions/setup-node@v3
    #           with:
    #               node-version: "16"
    #         - run: echo "Hello, World!"
